@url = http://localhost:8080/api/users

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "username": "admin@admin.com",
    "password": "admin",
    "role": "ROLE_USER"
}

###

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "username": "user@user.com",
    "password": "user",
    "role": "ROLE_USER"
}

###

POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "admin"
}

###

POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "user@user.com",
    "password": "user"
}

###

PUT {{url}}/register/admin/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3NzkzMDQ4ODUsImV4cCI6MTc3OTMwNjY4NX0.0nNAslpDdWoF90q3wANOjhnEer5rYKqnreElpkgDKmc