@url = http://localhost:8080/api/users

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "username": "a@a.com",
    "password": "a",
    "role": "USER"
}

###

POST {{url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "a@a.com",
    "password": "a"
}

###

GET {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhQGEuY29tIiwiaWF0IjoxNzc4OTcxNDg1LCJleHAiOjE3Nzg5NzE1OTN9.ZK8V2Mc_yhVghLfgq7iHsIKHyBSqx1yYbleIDGrevH4
Content-Type: application/json